### ISSUE TITLE
Cannot read property 'createSession' of undefined

### ISSUE THREAD

**Issue by lareinamarieyu** [testproject-io/javascript-opensdk#42]
Hello, I'm getting this error below while trying to initialize MobileBuilder(AndroidDriver). There's not much documentation on how to use it, so I figured to just post here instead.

```
describe("Basic Android Test", () => {
  let driver = AndroidDriver;

  before(async () => {
    driver = await new MobileBuilder(AndroidDriver)
    .withProjectName('My first Project')
    .withReportName("My first Project")
    .withCapabilities(
      {capabilities: {
        udid: android.udid,
        appPackage: testProject.appPackage,
        appActivity: testProject.appActivityUrl
      }})
    .withToken(testProject.developerToken)
    .withRemoteAgent(testProject.remoteAgentUrl)
    .build();
  });
});
```

### TypeError: Cannot read property 'createSession' of undefined
      at MobileBuilder.<anonymous> (node_modules/@tpio/javascript-opensdk/dist/src/sdk/drivers/mobileBuilder.js:24:36)
      at Generator.next (<anonymous>)
      at /home/iamgroot/Documents/repo/testproject_js/node_modules/@tpio/javascript-opensdk/dist/src/sdk/drivers/mobileBuilder.js:8:71
      at new Promise (<anonymous>)
      at __awaiter (node_modules/@tpio/javascript-opensdk/dist/src/sdk/drivers/mobileBuilder.js:4:12)
      at MobileBuilder.build (node_modules/@tpio/javascript-opensdk/dist/src/sdk/drivers/mobileBuilder.js:22:16)
      at Context.<anonymous> (file:///home/iamgroot/Documents/repo/testproject_js/tests/login_nonSubscriber.js:23:6)
      at processImmediate (internal/timers.js:464:21)

**Comment by s-glatshtein** [comment]
Thank you for opening this issue. We will investigate it and get back to you

**Comment by lareinamarieyu** [comment]
hi @vitalybu, yup. i also spoke to Tal from TestProject and he's looking into the issue as the MobileDriver doesn't seem to work as expected.
